name: CI

on:
  push:
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm qemu-system-x86 binutils make coreutils cpio
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src
      - name: Build and smoke test
        run: |
          make clean
          make smoke
